### PR TITLE
Added Czech localization

### PR DESCRIPTION
**Pull request by p-bo**
is line 94:

$LANG['processmaker']['item']['error'][100]=$LANG['processmaker']['item']['error'][11];

correct or two lines joined by accident?
(in both en_GB and fr_FR)

### CODE REVIEW

**Comment by tomolimo** [comment]
Hello @p-bo,
 
1. Thank you for your translation, I'll integrate as soon as I've time to do it (probably end of next week)
1. And yes, the mapping is by design and the reason is to be found here: http://wiki.processmaker.com/index.php/ProcessMaker_WSDL_Web_Services#Web_Services_Error_Numbers. In the list of error messages that the PM server web services can return at case creation: I got one time the 100 error when the process was invalid, and such I mapped this error code with the 11 one which seems to mean the same.

Thank you again,
Regards,
Tomolimo

**Comment by p-bo** [comment]
Thanks for explanation and thanks for all your work too! :)

**Comment by tomolimo** [comment]
Hello @p-bo 
I'm preparing a new release of the plugin, and there are new sentences :smiley: 
Would you agree to translate them?
I've prepared a Crowdin project for that: https://crowdin.com/project/processmaker-plugin
You may go there and register to the project, I'll approve your registration, and you'll be able to translate  the missing sentences into Czech.
Thank you,
Regards,
Tomolimo

**Comment by p-bo** [comment]
Hello @tomolimo 
thanks for letting me know, joined on crowdin. Would it be possible to give me rights to alter existing translations, even approved ones please?

Thanks and have a nice day :)
Pavel

**Comment by tomolimo** [comment]
Hello @p-bo 

Did you receive my message about lost of your translations?
I'm very sorry for that.
I've added you as proofreader: normally that's should be possible for you to un-approve existing approved translations.

Thank you,
Regards,
Tomolimo

**Comment by p-bo** [comment]
Yes I did - don't worry, it hapens...
Thanks, will do translations :)

P.

2018-08-02 17:08 GMT+02:00 tomolimo <notifications@github.com>:

**Comment by p-bo** [comment]
Done on crowdin - please merge :)

**Pull request merged**
